package com.miniStreaming.ch02.job;

/**
 * This Operator class is the base class for all user defined operators.
 * @param <I> The data type of the events in the incoming stream
 * @param <O> The data type of the events in the outgoing stream
 */
public abstract class Operator<I, O> implements IOperator<I, O> {
  protected Stream<O> outgoingStream = new Stream<O>();

  /**
   * Get the outgoing stream of the component.
   * @return The outgoing stream
   */
  public Stream<O> getOutgoingStream() { return outgoingStream; }

  /**
   * Apply logic to the incoming event and generate results.
   * The function is abstract and needs to be implemented by users.
   * @param event The incoming event
   * @return The results generated by the logic
   */
  public abstract O[] apply(I event);
}
